# Generated by Django 5.1.4 on 2025-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_customer_lead_delete_person_customer_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='retert',
            field=models.CharField(default='', max_length=255),
        ),
    ]
