# Generated by Django 5.1.4 on 2025-02-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_customer_retert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='retert',
        ),
    ]
