# Generated by Django 5.1.5 on 2025-02-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_customer_contact_person_customer_converted_from_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
